Move show docker logs to after docker compose is run

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -131,15 +131,6 @@ jobs:
       - name: List all running containers
         run: docker ps -a
 
-      - name: Show Docker logs
-        run: |
-          CONTAINER=$(docker ps --format '{{.Names}}' | grep graphql-api || true)
-          if [ -n "$CONTAINER" ]; then
-            docker logs "$CONTAINER"
-          else
-            echo "⚠️ graphql-api container not found."
-          fi
-
       - name: Login to DockerHub
         uses: docker/login-action@v2
         with:
@@ -164,7 +155,13 @@ jobs:
           docker compose --env-file .env up -d
 
       - name: Show Docker logs
-        run: docker logs $(docker ps --format '{{.Names}}' | grep graphql-api || true)
+        run: |
+          CONTAINER=$(docker ps --format '{{.Names}}' | grep graphql-api || true)
+          if [ -n "$CONTAINER" ]; then
+            docker logs "$CONTAINER"
+          else
+            echo "⚠️ graphql-api container not found."
+          fi
       
       - name: Verify Containers are up and running
         run: |
