Try using archive in repo and seeding from there

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -33,52 +33,37 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      - name: Upload archive folder (CSV)
+        uses: actions/upload-artifact@v3
+        with:
+          name: csv-archive
+          path: archive/
+        
       - name: Set up Docker Compose
         run: |
           sudo apt-get update
           sudo apt-get install -y docker-compose
-        
-      - name: Show Docker Compose config
-        run: docker compose config
-
-      - name: List all running containers
-        run: docker ps -a
-
-      - name: Login to DockerHub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-      
-      - name: Set up environment variables
-        run: |
-          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> .env
-          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
-          echo "NODEJS_EXPRESS_PORT=8081" >> .env
-          echo "DOCKER=true" >> .env
-          echo "DB_CONNECTION_STRING=mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017/graphql-api-db?authSource=admin" >> .env
-        
-      - name: Remove MongoDB volume to force fresh import
+          - name: Set env variables
+          run: |
+            echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> .env
+            echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
+            echo "NODEJS_EXPRESS_PORT=8081" >> .env
+            echo "DOCKER=true" >> .env
+            echo "DB_CONNECTION_STRING=mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017/graphql-api-db?authSource=admin" >> .env
+  
+      - name: Remove existing MongoDB volume
         run: docker volume rm assignment-graphql-api-design_mongo-data || true
 
+      - name: Download archive into repo
+        uses: actions/download-artifact@v3
+        with:
+          name: csv-archive
+          path: archive  # path inside container will be /app/archive
+
       - name: Run Docker Compose
-        run: |
-          docker compose --env-file .env up --build -d
+        run: docker compose --env-file .env up --build -d
 
       - name: Show Docker logs
-        run: |
-          CONTAINER=$(docker ps --format '{{.Names}}' | grep graphql-api || true)
-          if [ -n "$CONTAINER" ]; then
-            docker logs "$CONTAINER"
-          else
-            echo "⚠️ graphql-api container not found."
-          fi
-      
-      - name: Verify Containers are up and running
-        run: |
-          docker ps
-
-      - name: Print container logs before waiting
         run: docker logs graphql-api || true
 
       - name: Wait for API to be ready
@@ -86,111 +71,20 @@ jobs:
           echo "Waiting for GraphQL API to be ready..."
           for i in {1..20}; do
             if curl -s http://localhost:8081/graphql > /dev/null; then
-              echo "API is up!"
+              echo "✅ API is up!"
               exit 0
             fi
             echo "⏳ Waiting ($i)..."
             sleep 3
           done
-          exit 1
-          echo "❌ API did not start in time. Dumping logs:"
+          echo "❌ API not ready in time"
           docker logs graphql-api || true
           exit 1
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          push: true
-          tags: ${{ secrets.DOCKER_USERNAME }}/assignment-api-design-api:latest
-  
-  deploy:
-    runs-on : ubuntu-latest
-    needs: [build, docker]
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Install Docker
-        run: |
-          sudo apt-get update
-          curl -fsSL https://get.docker.com | sh
-
-      - name: Docker login
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-  test:
-    runs-on: ubuntu-latest
-    needs: [build, docker, deploy]
-
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Set up Docker Compose
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y docker-compose
-
-      - name: Set up environment variables
-        run: |
-          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> .env
-          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
-          echo "DB_CONNECTION_STRING=mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017/graphql-api-db?authSource=admin" >> .env
-
-      - name: Remove MongoDB volume to force fresh import
-        run: docker volume rm assignment-graphql-api-design_mongo-data || true
-
-      - name: Run Docker Compose
-        run: |
-          docker compose --env-file .env up --build -d
-        
-      - name: Run docker logs for debugging
-        run: docker compose logs app
-      
-      # - name: Seed database
-      #   run: docker exec graphql-api node seed.js
-
-      # - name: Restore MongoDB from dump
-      #   run: ./restore-db.sh
-      #   env:
-      #     MONGO_USER: ${{ secrets.MONGO_USER }}
-      #     MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
-
-      - name: Show Docker logs
-        run: |
-          CONTAINER=$(docker ps --format '{{.Names}}' | grep graphql-api || true)
-          if [ -n "$CONTAINER" ]; then
-            docker logs "$CONTAINER"
-          else
-            echo "⚠️ graphql-api container not found."
-          fi
-      
-      - name: Verify Containers are up and running
-        run: |
-          docker ps
-
-      - name: Wait for API to be ready
-        run: |
-          echo "Waiting for GraphQL API to be ready..."
-          for i in {1..20}; do
-            if curl -s http://localhost:8081/graphql > /dev/null; then
-              echo "API is up!"
-              exit 0
-            fi
-            echo "⏳ Waiting ($i)..."
-            sleep 3
-          done
-          exit 1
-
-      - name: Seed database
+      - name: Seed DB
         run: docker exec graphql-api node seed.js
 
-      - name: Check collections in MongoDB
+      - name: Verify collection sizes
         run: |
           echo "Movies count:"
           docker exec mongo mongosh --quiet --eval 'db = db.getSiblingDB("graphql-api-db"); db.movies.countDocuments()'
@@ -199,37 +93,265 @@ jobs:
           echo "Ratings count:"
           docker exec mongo mongosh --quiet --eval 'db = db.getSiblingDB("graphql-api-db"); db.ratings.countDocuments()'
 
-      - name: Install Newman
-        run: npm install -g newman
+      - name: Login to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Run Postman tests
-        run: |
-          newman run tests/collection5.json \
-            --environment tests/environment1.json \
-            --folder "registerUser (Success)" \
-            --folder "registerUser (Failure)" \
-            --folder "loginUser (Success)" \
-            --folder "loginUser (Failure)" \
-            --folder "refreshToken (Success)" \
-            --folder "refreshToken (Failure)" \
-            --folder "deleteUser (Success)" \
-            --folder "addMovie (Success)" \
-            --folder "addMovie (Failure)" \
-            --folder "movies (Success)" \
-            --folder "movies (Failure)" \
-            --folder "movie (Success)" \
-            --folder "movie (Failure)" \
-            --folder "updateMovie (Success)" \
-            --folder "updateMovie (Failure)" \
-            --folder "deleteMovie (Success)" \
-            --folder "deleteMovie (Failure)" \
-            --folder "ratings (Success)" \
-            --folder "ratings (Failure)" \
-            --folder "actors (Success)" \
-            --folder "actors (Failure)" \
-            --folder "Nested Query (Success)" \
-            --folder "Nested Query (Failure)" \
-            --delay-request 1000
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v4
+        with:
+          context: .
+          push: true
+          tags: ${{ secrets.DOCKER_USERNAME }}/assignment-api-design-api:latest
+  
+  test:
+      runs-on: ubuntu-latest
+      needs: docker
+  
+      steps:
+        - name: Checkout repo
+          uses: actions/checkout@v3
+  
+        - name: Install Newman
+          run: npm install -g newman
+
+        - name: Run Postman tests
+          run: |
+            newman run tests/collection5.json \
+              --environment tests/environment1.json \
+              --folder "registerUser (Success)" \
+              --folder "registerUser (Failure)" \
+              --folder "loginUser (Success)" \
+              --folder "loginUser (Failure)" \
+              --folder "refreshToken (Success)" \
+              --folder "refreshToken (Failure)" \
+              --folder "deleteUser (Success)" \
+              --folder "addMovie (Success)" \
+              --folder "addMovie (Failure)" \
+              --folder "movies (Success)" \
+              --folder "movies (Failure)" \
+              --folder "movie (Success)" \
+              --folder "movie (Failure)" \
+              --folder "updateMovie (Success)" \
+              --folder "updateMovie (Failure)" \
+              --folder "deleteMovie (Success)" \
+              --folder "deleteMovie (Failure)" \
+              --folder "ratings (Success)" \
+              --folder "ratings (Failure)" \
+              --folder "actors (Success)" \
+              --folder "actors (Failure)" \
+              --folder "Nested Query (Success)" \
+              --folder "Nested Query (Failure)" \
+              --delay-request 1000
+    
+  #     - name: Show Docker Compose config
+  #       run: docker compose config
+
+  #     - name: List all running containers
+  #       run: docker ps -a
+
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v2
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_PASSWORD }}
+      
+  #     - name: Set up environment variables
+  #       run: |
+  #         echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> .env
+  #         echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
+  #         echo "NODEJS_EXPRESS_PORT=8081" >> .env
+  #         echo "DOCKER=true" >> .env
+  #         echo "DB_CONNECTION_STRING=mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017/graphql-api-db?authSource=admin" >> .env
+        
+  #     - name: Remove MongoDB volume to force fresh import
+  #       run: docker volume rm assignment-graphql-api-design_mongo-data || true
+
+  #     - name: Run Docker Compose
+  #       run: |
+  #         docker compose --env-file .env up --build -d
+
+  #     - name: Show Docker logs
+  #       run: |
+  #         CONTAINER=$(docker ps --format '{{.Names}}' | grep graphql-api || true)
+  #         if [ -n "$CONTAINER" ]; then
+  #           docker logs "$CONTAINER"
+  #         else
+  #           echo "⚠️ graphql-api container not found."
+  #         fi
+      
+  #     - name: Verify Containers are up and running
+  #       run: |
+  #         docker ps
+
+  #     - name: Print container logs before waiting
+  #       run: docker logs graphql-api || true
+
+  #     - name: Wait for API to be ready
+  #       run: |
+  #         echo "Waiting for GraphQL API to be ready..."
+  #         for i in {1..20}; do
+  #           if curl -s http://localhost:8081/graphql > /dev/null; then
+  #             echo "API is up!"
+  #             exit 0
+  #           fi
+  #           echo "⏳ Waiting ($i)..."
+  #           sleep 3
+  #         done
+  #         exit 1
+  #         echo "❌ API did not start in time. Dumping logs:"
+  #         docker logs graphql-api || true
+  #         exit 1
+
+  #     - name: Build and push Docker image
+  #       uses: docker/build-push-action@v4
+  #       with:
+  #         context: .
+  #         push: true
+  #         tags: ${{ secrets.DOCKER_USERNAME }}/assignment-api-design-api:latest
+  
+  # deploy:
+  #   runs-on : ubuntu-latest
+  #   needs: [build, docker]
+
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+
+  #     - name: Install Docker
+  #       run: |
+  #         sudo apt-get update
+  #         curl -fsSL https://get.docker.com | sh
+
+  #     - name: Docker login
+  #       uses: docker/login-action@v2
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_PASSWORD }}
+
+  # test:
+  #   runs-on: ubuntu-latest
+  #   needs: [build, docker, deploy]
+
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
+
+  #     - name: Set up Docker Compose
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt-get install -y docker-compose
+
+  #     - name: Set up environment variables
+  #       run: |
+  #         echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> .env
+  #         echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
+  #         echo "DB_CONNECTION_STRING=mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@mongo:27017/graphql-api-db?authSource=admin" >> .env
+
+  #     - name: Remove MongoDB volume to force fresh import
+  #       run: docker volume rm assignment-graphql-api-design_mongo-data || true
+
+  #     - name: Run Docker Compose
+  #       run: |
+  #         docker compose --env-file .env up --build -d
+        
+  #     - name: Run docker logs for debugging
+  #       run: docker compose logs app
+      
+  #     # - name: Seed database
+  #     #   run: docker exec graphql-api node seed.js
+
+  #     # - name: Restore MongoDB from dump
+  #     #   run: ./restore-db.sh
+  #     #   env:
+  #     #     MONGO_USER: ${{ secrets.MONGO_USER }}
+  #     #     MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
+
+  #     - name: Show Docker logs
+  #       run: |
+  #         CONTAINER=$(docker ps --format '{{.Names}}' | grep graphql-api || true)
+  #         if [ -n "$CONTAINER" ]; then
+  #           docker logs "$CONTAINER"
+  #         else
+  #           echo "⚠️ graphql-api container not found."
+  #         fi
+      
+  #     - name: Verify Containers are up and running
+  #       run: |
+  #         docker ps
+
+  #     - name: Wait for API to be ready
+  #       run: |
+  #         echo "Waiting for GraphQL API to be ready..."
+  #         for i in {1..20}; do
+  #           if curl -s http://localhost:8081/graphql > /dev/null; then
+  #             echo "API is up!"
+  #             exit 0
+  #           fi
+  #           echo "⏳ Waiting ($i)..."
+  #           sleep 3
+  #         done
+  #         exit 1
+
+  #     - name: Upload CSV archive
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: csv-archive
+  #         path: archive/
+  #     - name: Download CSV archive
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: csv-archive
+  #         path: archive
+        
+  #     - name: Move archive into container build context
+  #       run: mv archive ./archive
+
+  #     - name: Check if archive directory exists
+  #       run: docker exec graphql-api ls -l /app/archive || true
+
+  #     - name: Seed database
+  #       run: docker exec graphql-api node seed.js
+
+  #     - name: Check collections in MongoDB
+  #       run: |
+  #         echo "Movies count:"
+  #         docker exec mongo mongosh --quiet --eval 'db = db.getSiblingDB("graphql-api-db"); db.movies.countDocuments()'
+  #         echo "Actors count:"
+  #         docker exec mongo mongosh --quiet --eval 'db = db.getSiblingDB("graphql-api-db"); db.actors.countDocuments()'
+  #         echo "Ratings count:"
+  #         docker exec mongo mongosh --quiet --eval 'db = db.getSiblingDB("graphql-api-db"); db.ratings.countDocuments()'
+
+      # - name: Run Postman tests
+      #   run: |
+      #     newman run tests/collection5.json \
+      #       --environment tests/environment1.json \
+      #       --folder "registerUser (Success)" \
+      #       --folder "registerUser (Failure)" \
+      #       --folder "loginUser (Success)" \
+      #       --folder "loginUser (Failure)" \
+      #       --folder "refreshToken (Success)" \
+      #       --folder "refreshToken (Failure)" \
+      #       --folder "deleteUser (Success)" \
+      #       --folder "addMovie (Success)" \
+      #       --folder "addMovie (Failure)" \
+      #       --folder "movies (Success)" \
+      #       --folder "movies (Failure)" \
+      #       --folder "movie (Success)" \
+      #       --folder "movie (Failure)" \
+      #       --folder "updateMovie (Success)" \
+      #       --folder "updateMovie (Failure)" \
+      #       --folder "deleteMovie (Success)" \
+      #       --folder "deleteMovie (Failure)" \
+      #       --folder "ratings (Success)" \
+      #       --folder "ratings (Failure)" \
+      #       --folder "actors (Success)" \
+      #       --folder "actors (Failure)" \
+      #       --folder "Nested Query (Success)" \
+      #       --folder "Nested Query (Failure)" \
+      #       --delay-request 1000
 
       # - name: Run remaining Postman tests
       #   run: |
